### ISSUE TITLE
@hrbrmstr's notes

### ISSUE THREAD

**Issue by hrbrmstr** [Grey-Noise-Intelligence/api.greynoise.io#1]
I have to do some R7 work for a while but I wanted to leave this placeholder for me to come back to later.

**Comment by andrew-morris** [comment]
👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼

**Comment by hrbrmstr** [comment]
# API

- [ ] prep for pagination now vs later. i grok that current list of scanners is manageable, but we'll be in IPv6 land sooner than later (close to 20% adoption rate now) and there are likely more startups and evildoers than we both imagine out there
- [ ] consistent status returns. "ok", "exists", heck even "steve" – the text return for extra words for 200 or otherwise shld be consistent across endpoints
- [ ] pretty names; tags shld have programmatic (the SNAKE_CAPS_CASE ones) and also "pretty" ones with descriptions. perhaps another endpoint
- [ ] throttling/rate limiting; thx to the abuse Sonar data downloads get, I know all too well how selfish startups, researchers and adversaries can be. API keys and rate limiting shld be in sooner than later.
- [ ] voluntary submission data from research orgs; have a way research orgs (like R7, shadowserver, etc) can maintain contact info and submit/maintain node data; not saying trust them 100% but let them be a partner

# Other

As you build this out, you have my volunteer offer to have a dashboard, network graph aid, etc. not sure where you want to take this, but it is truly an almost invaluable resource for defenders & researchers.  However I or other can help make this be as spiffy as possible, just jot stuff down and we'll all try to flesh it out.

**Comment by andrew-morris** [comment]
This is amazing feedback. I'm going to cut this into separate tickets for independent tracking and close this out.

**Comment by andrew-morris** [comment]
@hrbrmstr went ahead and cut ~6 tickets out of this. I can probably knock at least a few of these out this afternoon. gonna go ahead and close this ticket. thanks again!
