### ISSUE TITLE
Known IP Endpoints Request

### ISSUE THREAD

**Issue by foospidy** [Grey-Noise-Intelligence/api.greynoise.io#15]
Request for new endpoint(s), something like...

/vX/query/known_ip - returns true if grey noise has seen this ip, else false.
/vX/query/known_ip_low - returns true if grey noise has seen this ip and rates it low confidence, else false.
/vX/query/known_ip_medium - returns true if grey noise has seen this ip and rates it medium confidence, else false.
/vX/query/known_ip_high - returns true if grey noise has seen this ip and rates it high confidence, else false.

or it could be...
/vX/query/known_ip - if grey noise has seen this ip returns the confidence level (low/med/high), else returns false (or unknown).

**Comment by andrew-morris** [comment]
Rock and roll. Thanks!
