### ISSUE TITLE
Tell Vinnie I said hey 👋

### ISSUE THREAD

**Issue by AndrewAskins** [Grey-Noise-Intelligence/api.greynoise.io#8]
I would like for you to tell Vinnie I said hey.

**Comment by andrew-morris** [comment]
@AndrewAskins marking this critical - resolving ASAP

**Comment by AndrewAskins** [comment]
Checking back to see if we have a timeline on this yet.

**Comment by foospidy** [comment]
I'm waiting on this as well.

**Comment by andrew-morris** [comment]
FaceTimed Vinnie, said hey. Issue resolved. God bless.
